package cardio_app.util;

import android.content.res.Resources;
import android.graphics.Color;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import cardio_app.R;
import cardio_app.activity.statistics.ChartActivity;
import cardio_app.db.model.PressureData;
import lecho.lib.hellocharts.model.Axis;
import lecho.lib.hellocharts.model.AxisValue;
import lecho.lib.hellocharts.model.Line;
import lecho.lib.hellocharts.model.LineChartData;
import lecho.lib.hellocharts.model.PointValue;

public class ChartBuilder {
    private static final long MILLIS_IN_DAY = 24 * 3600 * 1000;
    private List<PressureData> data;
    private ChartMode chartMode = ChartMode.DISCRETE;

    private Resources resources;
    private long days;

    public ChartBuilder(List<PressureData> data, Resources resources) {
        this.data = data;
        this.resources = resources;
    }

    public ChartBuilder setData(List<PressureData> data) {
        this.data = data;

        return this;
    }

    public ChartBuilder setMode(ChartMode chartMode) {
        this.chartMode = chartMode;

        return this;
    }

    public long getDays() {
        return days;
    }

    public LineChartData build() {
        List<Line> lines = new ArrayList<>();
        switch (chartMode) {
            case DISCRETE: {
                for (PressureData entity : data) {
                    List<PointValue> once = new ArrayList<>();
                    once.add(new ChartActivity.CustomPointValue(entity.getDateTime().getTime(), entity.getSystole(), entity));
                    once.add(new ChartActivity.CustomPointValue(entity.getDateTime().getTime(), entity.getDiastole(), entity));

                    lines.add(new Line(once).setColor(Color.RED));
                }

                break;
            }
            case CONTINUOUS: {
                List<PointValue> diastoles = new ArrayList<>();
                List<PointValue> systoles = new ArrayList<>();

                for (PressureData entity : data) {
                    diastoles.add(new ChartActivity.CustomPointValue(entity.getDateTime().getTime(), entity.getDiastole(), entity));
                    systoles.add(new ChartActivity.CustomPointValue(entity.getDateTime().getTime(), entity.getSystole(), entity));
                }

                lines.add(new Line(diastoles).setColor(Color.GREEN));
                lines.add(new Line(systoles).setColor(Color.RED));

                break;
            }
        }

        long min = 0, max = 0, diff = 0;

        if (data.size() > 0) {
            min = data.get(data.size() - 1).getDateTime().getTime();
            max = data.get(0).getDateTime().getTime();
            diff = max - min;
        }
        days = diff / MILLIS_IN_DAY;

        //x axis with formatted date
        DateFormat simpleDateFormat = SimpleDateFormat.getDateInstance();
        List<AxisValue> aList = new ArrayList<>();
        Calendar calendar = Calendar.getInstance();
        for (long a = min; a <= max; a += MILLIS_IN_DAY) {
            calendar.setTimeInMillis(a);
            calendar.set(Calendar.HOUR_OF_DAY, 0);
            calendar.set(Calendar.MINUTE, 0);
            calendar.set(Calendar.SECOND, 0);
            String value = simpleDateFormat.format(new Date(calendar.getTimeInMillis()));
            aList.add(new AxisValue(calendar.getTimeInMillis(), value.toCharArray()));
        }

        Axis axisY = new Axis()
                .setName(resources.getString(R.string.label_axis_y))
                .setTextColor(Color.BLACK)
                .setHasLines(true)
                .setAutoGenerated(true);

        Axis axisX = new Axis()
                .setName(resources.getString(R.string.label_axis_x))
                .setTextColor(Color.BLACK)
                .setHasLines(true)
                .setMaxLabelChars(12)
                .setValues(aList);

        LineChartData chartData = new LineChartData(lines);
        chartData.setAxisYLeft(axisY);
        chartData.setAxisXBottom(axisX);

        return chartData;
    }

    public enum ChartMode {
        DISCRETE, CONTINUOUS
    }
}
